//
// Created by berke on 4/29/2026.
//

#ifndef TILKY_ENGINE_CONFIG_H
#define TILKY_ENGINE_CONFIG_H

#define MAX_FLOOR_COUNT 6
#define BOUNDARY_COUNT (MAX_FLOOR_COUNT + 1)

#endif //TILKY_ENGINE_CONFIG_H