#include "Headers/Runtime/Scripting/Lua/LuaBindingMetadata.hpp"

#include <fstream>
#include <utility>

#include <spdlog/spdlog.h>

namespace {
    std::vector<LuaBindingMetadata::TypeDoc> registeredTypes;
}

namespace LuaBindingMetadata {
    void RegisterType(TypeDoc type) {
        registeredTypes.push_back(std::move(type));
    }

    const std::vector<TypeDoc>& AllTypes() {
        return registeredTypes;
    }

    bool GenerateLuaLSStub(const std::string& outputPath) {
        std::ofstream file(outputPath);

        if (!file.is_open()) {
            spdlog::error("Failed to open '{}' for LuaLS stub generation", outputPath);
            return false;
        }

        file << "---@meta\n";
        file << "-- Auto-generated by Tilky's LuaBindingMetadata registry - do not edit by\n";
        file << "-- hand, regenerate instead. Point LuaLS's Lua.workspace.library at this\n";
        file << "-- file's folder for autocomplete/hover/signature-help on Tilky's scripting API.\n\n";

        for (const TypeDoc& type : registeredTypes) {
            if (!type.doc.empty()) file << "---" << type.doc << "\n";
            file << "---@class " << type.name << "\n";

            for (const PropertyDoc& prop : type.properties) {
                file << "---@field " << prop.name << " " << prop.luaType;
                if (!prop.doc.empty()) file << " @" << prop.doc;
                file << "\n";
            }

            file << "local " << type.name << " = {}\n\n";

            for (const MethodDoc& method : type.methods) {
                if (!method.doc.empty()) file << "---" << method.doc << "\n";

                for (const ParamDoc& param : method.params)
                    file << "---@param " << param.name << " " << param.luaType << "\n";

                if (!method.returnType.empty()) file << "---@return " << method.returnType << "\n";

                file << "function " << type.name << ":" << method.name << "(";

                for (std::size_t i = 0; i < method.params.size(); ++i) {
                    if (i > 0) file << ", ";
                    file << method.params[i].name;
                }

                file << ") end\n\n";
            }
        }

        return true;
    }
}
